version: '3.8'

services:
  5core-server:
    image: 360760094043.dkr.ecr.ap-northeast-2.amazonaws.com/5core:latest
    ports:
      - "80:8090"   # 호스트 80 포트 → 컨테이너 8090
    environment:
      # 필요하면 AWS RDS 연결 정보 환경 변수로 설정 가능
      SPRING_DATASOURCE_URL: jdbc:mysql://<AWS-RDS-ENDPOINT>:3306/5core
      SPRING_DATASOURCE_USERNAME: dbmasteruser
      SPRING_DATASOURCE_PASSWORD: Acw8&vV#7)q8W1dr.|;dlUMh=Dy*2rA`