spring.application.name=5core

# 포트 번호 변경
server.port=8090

# 프로젝트 실행 경로 설정
# - URL에 아래의 기본 쇼핑몰 경로를 추가함
server.servlet.context-path=/5core


# HTTP요청으로 RESTful 웹서비스를 사용하도록 하는 설정
# - GET(조회), POST(저장), PUT(수정), DELETE(삭제)를 적용하는 설정
spring.mvc.hiddenmethod.filter.enabled=true

# devtools 설정 - 저장 시 자동 실행(true)
spring.devtools.restart.enabled=false

# MySQL 설정 (localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/5core
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=hm01
spring.datasource.password=1234

# 서버를 기동할 때 data.sql 파일을 실행하는 설정
# always: data.sql 파일을 실행, never: data.sql 파일을 실행하지 않음
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# JPA 설정
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

# 파일 업로드 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=c:/5core
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB



